import { PdfCtx, fillPage, drawText, colors, decisionColor } from "../pdfHelpers";
import { ApplicationProfile } from "../../applicationTypes";
import { CamDataset } from "../../camData";

export function drawCoverPage(ctx: PdfCtx, dataset: ApplicationProfile, camData: CamDataset) {
  fillPage(ctx);
  const { doc, pageW, margin } = ctx;
  const ph = doc.internal.pageSize.getHeight();
  const cx = pageW / 2;

  // Top navy band
  doc.setFillColor(...colors.primary);
  doc.rect(0, 0, pageW, 40, "F");
  drawText(ctx, "INTELLICREDIT", cx, 18, { size: 22, color: colors.white, style: "bold", align: "center" });
  drawText(ctx, "AI-Powered Credit Risk Assessment Platform", cx, 28, { size: 8, color: [180, 200, 230], align: "center" });

  // Divider line
  doc.setFillColor(...colors.primary);
  doc.rect(margin, 48, pageW - margin * 2, 0.5, "F");

  // Report type
  drawText(ctx, "CREDIT APPRAISAL MEMORANDUM", cx, 65, { size: 16, color: colors.dark, style: "bold", align: "center" });

  // Company card
  doc.setFillColor(...colors.cardBg);
  doc.roundedRect(margin + 20, 75, pageW - margin * 2 - 40, 40, 3, 3, "F");
  doc.setDrawColor(...colors.border);
  doc.roundedRect(margin + 20, 75, pageW - margin * 2 - 40, 40, 3, 3, "S");

  drawText(ctx, dataset.companyName, cx, 88, { size: 14, color: colors.dark, style: "bold", align: "center" });
  drawText(ctx, `CIN: ${dataset.cin}`, cx, 96, { size: 8, color: colors.muted, align: "center" });
  drawText(ctx, `Sector: ${dataset.sector}  ·  Loan Request: ₹${dataset.loanAmount}`, cx, 103, { size: 8, color: colors.muted, align: "center" });
  drawText(ctx, `Purpose: ${dataset.purpose}`, cx, 110, { size: 8, color: colors.muted, align: "center" });

  // Decision badge
  const badgeColor = decisionColor[camData.recommendation.decision];
  const badgeW = 50;
  doc.setFillColor(...badgeColor);
  doc.roundedRect(cx - badgeW / 2, 125, badgeW, 12, 2, 2, "F");
  const badgeLabel = camData.recommendation.decision === "reject" ? "REJECTED" : camData.recommendation.decision === "approve" ? "APPROVED" : "CONDITIONAL";
  drawText(ctx, badgeLabel, cx, 132.5, { size: 11, color: colors.white, style: "bold", align: "center" });

  // Report metadata
  drawText(ctx, "REPORT DETAILS", margin + 20, 155, { size: 7, color: colors.primary, style: "bold" });
  doc.setDrawColor(...colors.border);
  doc.line(margin + 20, 158, pageW - margin - 20, 158);

  const meta = [
    ["Report Reference", `IC-CAM-${dataset.id.toUpperCase()}-${new Date().getFullYear()}`],
    ["Generated", camData.generatedAt],
    ["Classification", "STRICTLY CONFIDENTIAL"],
    ["Prepared By", "IntelliCredit AI Engine v2.0"],
    ["Review Authority", "Credit Committee"],
  ];
  meta.forEach(([k, v], i) => {
    const yy = 165 + i * 6;
    drawText(ctx, k, margin + 20, yy, { size: 6.5, color: colors.muted });
    drawText(ctx, v, margin + 65, yy, { size: 7, color: colors.text });
  });

  // Bottom band
  doc.setFillColor(...colors.primary);
  doc.rect(0, ph - 25, pageW, 25, "F");
  drawText(ctx, "This document is generated by AI and is intended for internal credit assessment purposes only.", cx, ph - 16, {
    size: 5.5, color: [180, 200, 230], align: "center",
  });
  drawText(ctx, "All data points are sourced from verified documents and should be independently validated before final decision.", cx, ph - 11, {
    size: 5.5, color: [180, 200, 230], align: "center",
  });
}
