import { PdfCtx, sectionHeader, drawText, drawWrappedText, checkPage, colors } from "../pdfHelpers";

export function drawDisclaimer(ctx: PdfCtx, sectionNum: number) {
  sectionHeader(ctx, sectionNum, "Disclaimer & Authorization");

  drawWrappedText(ctx, "DISCLAIMER: This Credit Appraisal Memorandum has been generated by the IntelliCredit AI Engine using data sourced from uploaded financial documents, government databases (MCA21, GSTN, CIBIL, CERSAI, eCourts), and account aggregator feeds. While the AI system employs advanced natural language processing (FinBERT) and machine learning models for analysis, the output should be treated as a decision-support tool and not as a final credit decision.");

  drawWrappedText(ctx, "All findings, risk scores, and recommendations should be independently verified by the credit officer and approved through the appropriate sanctioning authority as per the institution's credit policy. The AI-generated scores and probabilities are statistical estimates and may not account for all qualitative factors.");

  drawWrappedText(ctx, "This report is strictly confidential and intended solely for internal credit assessment purposes. Unauthorized distribution or reproduction is prohibited.");

  ctx.y += 8;
  checkPage(ctx, 30);

  // Signature blocks
  drawText(ctx, "AUTHORIZATION", ctx.margin + 4, ctx.y, { size: 7, color: colors.primary, style: "bold" });
  ctx.y += 8;

  const sigW = ctx.contentW / 3;
  const sigs = ["Prepared By", "Reviewed By", "Approved By"];
  sigs.forEach((title, i) => {
    const x = ctx.margin + i * sigW;
    ctx.doc.setDrawColor(...colors.muted);
    ctx.doc.line(x + 4, ctx.y + 12, x + sigW - 8, ctx.y + 12);
    drawText(ctx, title, x + 4, ctx.y + 17, { size: 6, color: colors.muted });
    drawText(ctx, "Name: _______________", x + 4, ctx.y + 22, { size: 5.5, color: colors.muted });
    drawText(ctx, "Date: _______________", x + 4, ctx.y + 26, { size: 5.5, color: colors.muted });
    drawText(ctx, "Designation: ________", x + 4, ctx.y + 30, { size: 5.5, color: colors.muted });
  });
  ctx.y += 35;
}
